
apiVersion: v1
kind: Namespace
metadata:
  name: hparipai-ns
--- 
apiVersion: apps/v1
kind: Deployment
metadata:
    name: hpa-example
    namespace: hparipai-ns
spec:
    replicas: 3
    selector:
      matchLabels:
        app: hpa-example
    template:
        metadata:
            name: hpa-example
            
            labels:
                app: hpa-example
        spec:
            containers:
            - name: hpa-example
              image: ronenben/streamlit:latest
              ports:
              - name: http-port
                containerPort: 8501
              resources:
                  requests:
                      cpu: 200m
                  limits:
                      cpu: 200m

---
apiVersion: v1
kind: Service
metadata:
    name: hpa-example-svc
    namespace: hparipai-ns
spec:
    type: LoadBalancer
    selector:
        app: hpa-example
    ports:
    - port: 31001
      nodePort: 31001
      targetPort: http-port
      protocol: TCP
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
    name: hpa-example-autoscaler
    namespace: hparipai-ns
spec:
    scaleTargetRef:
        apiVersion: apps/v1
        kind: Deployment
        name: hpa-example
    minReplicas: 3
    maxReplicas: 32
    targetCPUUtilizationPercentage: 50
